version: "3.8"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile..dev
    command: npm run watch:all
    volumes:
      - ./dist:/dist
      - ./src:/src
      - ./logs:/logs
    ports:
      - "3000:3000"
    restart: always
    environment:
      NODE_ENV: development
